### ISSUE TITLE
컴포넌트 라이브러리 설치

### ISSUE THREAD

**Issue by jgjgill** [grow-playground/type-time#24]
# ✨ Feature

제 기억이 맞으면 [shadcn/ui](https://ui.shadcn.com/) 이 라이브러리 이야기가 나왔던 것 같습니다.
테이블, 아코디언, 탭, 모달, ... 등 적절하게 사용하면 좋을 것 같습니다.

## Description

현재 어떤 기능 구현을 진행중인지 간단하게 한줄로 작성해주세요.

## To-do

- [x] shadcn/ui 설치
- [x] 아코디언 설치해서 적용되는지 확인
- [x] 기존 스타일들 확인

## 기타

따로 팀원과 상의가 필요한 부분들을 적는 공간입니다.
