### ISSUE TITLE
메인 페이지 퀴즈 컴포넌트 작업

### ISSUE THREAD

**Issue by jgjgill** [grow-playground/type-time#30]
# ✨ Feature

## Description

현재 어떤 기능 구현을 진행중인지 간단하게 한줄로 작성해주세요.

메인 페이지에 있는 퀴즈 컴포넌트 작업을 진행합니다.
필터, 검색 기능은 구현하지 않고 디자인만 맞게 맞추려고 합니다.
데이터는 받아올 수 있을 것 같아서 이와 관련된 기능도 구현해보겠습니다.

<img width="345" alt="스크린샷 2023-12-22 오후 2 29 53" src="https://github.com/grow-playground/type-time/assets/79239852/c977d904-5a11-43d2-ae81-c7fe13e48f90">

## To-do

`@tanstack/react-table`도 활용해야 합니다.

- [x] 기본 데이터 테이블 구성
- [x] 난이도 필터 적용
- [x] 드롭다운 컴포넌트 적용
- [x] 검색 기능
- [x] 페이지네이션 기능
- [x] 퀴즈 데이터 받아오기
- [x] zod 데이터 유효성 검사하기

## 기타

따로 팀원과 상의가 필요한 부분들을 적는 공간입니다.
