### ISSUE TITLE
테이블 디자인 작업

### ISSUE THREAD

**Issue by jgjgill** [grow-playground/type-time#55]
# ✨ Feature

## Description

현재 어떤 기능 구현을 진행중인지 간단하게 한줄로 작성해주세요.

## To-do

- [x] 테이블 레이아웃 손보기
- [x] 아이콘 및 색상 주기
- [x] 메인 페이지 전체적인 디자인 작업

## 기타

따로 팀원과 상의가 필요한 부분들을 적는 공간입니다.
